version: '3.9'

services:
  next:
    image: node:16.1.0-alpine
    working_dir: /app
    command: yarn dev
    environment:
      TZ: Asia/Tokyo
    volumes:
      - $PWD:/app
    ports:
      - '3000:3000'
